// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VolunteerCenter.Data;

#nullable disable

namespace MinimalAPI.Migrations
{
    [DbContext(typeof(VolunteerCenterContext))]
    [Migration("20260508142046_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("VolunteerCenter.Models.Beneficiary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Beneficiaries");
                });

            modelBuilder.Entity("VolunteerCenter.Models.Specialist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Specialists");
                });

            modelBuilder.Entity("VolunteerCenter.Models.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CuratorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CuratorId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("VolunteerCenter.Models.VolunteerBeneficiary", b =>
                {
                    b.Property<int>("VolunteerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeneficiaryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("TEXT");

                    b.HasKey("VolunteerId", "BeneficiaryId");

                    b.HasIndex("BeneficiaryId");

                    b.ToTable("VolunteerBeneficiaries");
                });

            modelBuilder.Entity("VolunteerCenter.Models.Volunteer", b =>
                {
                    b.HasOne("VolunteerCenter.Models.Specialist", "Curator")
                        .WithMany("Volunteers")
                        .HasForeignKey("CuratorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Curator");
                });

            modelBuilder.Entity("VolunteerCenter.Models.VolunteerBeneficiary", b =>
                {
                    b.HasOne("VolunteerCenter.Models.Beneficiary", "Beneficiary")
                        .WithMany("VolunteerBeneficiaries")
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolunteerCenter.Models.Volunteer", "Volunteer")
                        .WithMany("VolunteerBeneficiaries")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiary");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("VolunteerCenter.Models.Beneficiary", b =>
                {
                    b.Navigation("VolunteerBeneficiaries");
                });

            modelBuilder.Entity("VolunteerCenter.Models.Specialist", b =>
                {
                    b.Navigation("Volunteers");
                });

            modelBuilder.Entity("VolunteerCenter.Models.Volunteer", b =>
                {
                    b.Navigation("VolunteerBeneficiaries");
                });
#pragma warning restore 612, 618
        }
    }
}
